### ISSUE TITLE
Dnsruby docs hopelessly outdated

### ISSUE THREAD

**Issue by alexdalitz** [spotify/rspec-dns#19]
Hi - 

Just a quick note to observe that your readme referencs dnsruby documentation for veriosn 1.0, which is almost ten years old. I think the current documentation is on my github site somewhere - although I'd be happy to update the dnsruby docs on a new dnsruby site, if it helped...

Thanks,

Alex.

**Comment by vzctl** [comment]
Hi Alex,

Thank you for pointing out the problem, I updated the links in f1f11e8beafd0e1b4b0f76c7f14fa24fa1cb28bd.

And, by the way, thank you for your work on dnsruby!
